"""Content schema for LLM-generated documents.

Simple JSON structure that LLM outputs and renderers consume.
"""
from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field


class ContentSection(BaseModel):
    """One section of the document."""

    id: str = Field(description="Unique section ID")
    title: str = Field(description="Section title")
    type: Literal["text", "bullets", "table", "chart"] = Field(
        description="Content type"
    )
    content: str | list[str] | list[list[str]] = Field(
        description="Section content (string for text, list for bullets/table rows)"
    )
    metadata: dict = Field(
        default_factory=dict,
        description="Section metadata (audience, emphasis, etc.)"
    )


class GeneratedContent(BaseModel):
    """Complete document content generated by LLM."""

    title: str = Field(description="Document title")
    subtitle: Optional[str] = Field(default="", description="Document subtitle")
    sections: list[ContentSection] = Field(
        default_factory=list,
        description="Document sections in order"
    )
    metadata: dict = Field(
        default_factory=dict,
        description="Document metadata (audience, date, type, etc.)"
    )

    def to_dict(self) -> dict:
        """Convert to plain dict for storage."""
        return self.model_dump()

    @classmethod
    def from_dict(cls, data: dict) -> GeneratedContent:
        """Load from stored dict."""
        return cls(**data)
